### ISSUE TITLE
Rpi.GPIO library

### ISSUE THREAD

**Issue by joearkay** [balena-io-projects/balena-node-red#14]
Hi all,

Very new to balena but extremely familar with Node Red. Once installed on a Pi 3, the logs show that the Pi GPIO library is not installed. 

Alongside this I added the modbus node to my palette but this won’t install due to a dependency on serial libraries. Is there a way a I can include this in the docker container to be rolled out automatically for future deployments?

Thanks

**Comment by kanr** [comment]
I think that submitting a Pull request with a patch to correctly install the rpi.gpio library would be in the scope of this repo but the modbus addition would not be and you should fork it. 

I have fixed the rpi.gpio dependency before so I can submit a PR as well if thats helpful.

**Comment by joearkay** [comment]
@kanr if you could submit a PR that would be fab 👍 - I'll fork and do the modbus part. Thanks :)

**Comment by kanr** [comment]
@joearkay you can merge the above PR into your fork and should now be able to use the UART and I2C nodes in node-red. I am a pretty big fan of Node-Red + Balena and have done lots of experimenting so feel free to reach out if you want/need more help.

**Comment by joearkay** [comment]
@kanr - have pulled this in and will set up now - thanks!

**Comment by joearkay** [comment]
@kanr I’ve taken up your offer on reaching out on the forum! Hope that’s ok!

https://forums.balena.io/t/node-red-on-pi-3-to-use-gpio-and-serial-modbus/4444
