### ISSUE TITLE
Siemens IoT2000/2040 - "Pull access denied for balenalib/iot2000-alpine-node, repository does not exist or may require 'docker login'"

### ISSUE THREAD

**Issue by joearkay** [balena-io-projects/balena-node-red#20]
I've started a forum post here discussing. I've started to look into fixes, but if anyone has any suggestions I'm all ears open! 

 https://forums.balena.io/t/node-red-on-siemens-iot-2040/25564

**Comment by curcuz** [comment]
@joearkay I just released 2.x that is based on debian base images, so your IOT20XX will be happy :)

**Comment by joearkay** [comment]
Awesome - thanks :)
