### ISSUE TITLE
node-red env variables in development mode

### ISSUE THREAD

**Issue by esaheiskanen** [balena-io-projects/balena-node-red#9]
Hi!

How can I define USERNAME and PASSWORD env variables when developing in local mode? I tried to add them to docker file without success 
```
ENV PASSWORD="YYYY" \
        USERNAME="XXX"
```

**Comment by esaheiskanen** [comment]
Ok, I think i found solution from resin-cli: https://docs.resin.io/tools/cli/#envs

**Comment by esaheiskanen** [comment]
Added USERNAME and PASSWORD as envs but still no go. maybe because of dollar sign at the beginning of the hash?
```
sudo resin envs --device XYZ       
ID    NAME     VALUE
56468 PASSWORD $xxxxxxxxxxxxxxxx
50925 PORT     80
56469 USERNAME yyyyyyyyy
```

**Comment by curcuz** [comment]
hi @esaheiskanen do you mean Local Mode?

**Comment by curcuz** [comment]
if so, please refer to this: https://docs.resin.io/development/local-mode/

>In your code you will still have access to most of the regular resin.io device features. For example, you will still be able to query and use the supervisor API. However, you will notice that your local mode device will not push logs back to the resin.io dashboard and you won't be able to set environment variables from the dashboard, but you can set them in you .resin-sync.yml.
